# Default values for metrics-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

labels:
  role: api
  tier: backend
  component: api

image:
  registry: 'docker.io/pagerinc'
  tag: '0.1'
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 3000

resources: {}

env:
  NODE_ENV: production

# Optionally specify an array of imagePullSecrets.
# Secrets must be manually created in the namespace.
# ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecrets: []
