apiVersion: v1
kind: Service
metadata:
  name: {{ template "metrics.fullname" . }}
  labels:
{{include "metrics.release_labels" . | indent 4}}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.internalPort | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name | default .Chart.Name }}
  selector:
    app: {{ .Chart.Name | quote }}
